/users/{id}/deactivate:
  put:
    summary: Desativa um usuário
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: ID do usuário a ser desativado
    responses:
      "200":
        description: Usuário desativado com sucesso
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                user:
                  type: object
                  properties:
                    _id:
                      type: string
                    username:
                      type: string
                    active:
                      type: boolean
                    createdAt:
                      type: string
                      format: date-time
      "404":
        description: Usuário não encontrado
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      "500":
        description: Erro ao desativar o usuário
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                error:
                  type: string
